version: '3.9'

services:
  gate-service:
    image: "gate-service:dev"
    container_name: gate-service
    ports:
      - "8088:8088"
    environment:
      SERVER_PORT: 8088
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8088/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 5